
# This file is automatically generated, you probably don't want to edit this

RCIOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "RCIOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            predictors = NULL,
            id = NULL,
            group = NULL,
            refgroup = NULL,
            newgroup = NULL,
            maximum = NULL,
            regtype = "logistic",
            percentile = NULL, ...) {

            super$initialize(
                package="LogisticRCI",
                name="RCI",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..predictors <- jmvcore::OptionVariables$new(
                "predictors",
                predictors)
            private$..id <- jmvcore::OptionVariable$new(
                "id",
                id)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..refgroup <- jmvcore::OptionInteger$new(
                "refgroup",
                refgroup,
                min=-10000000,
                max=10000000)
            private$..newgroup <- jmvcore::OptionInteger$new(
                "newgroup",
                newgroup,
                min=-10000000,
                max=10000000)
            private$..maximum <- jmvcore::OptionInteger$new(
                "maximum",
                maximum,
                min=0,
                max=1000000)
            private$..regtype <- jmvcore::OptionList$new(
                "regtype",
                regtype,
                options=list(
                    "linear",
                    "logistic"),
                default="logistic")
            private$..percentile <- jmvcore::OptionList$new(
                "percentile",
                percentile,
                options=list(
                    "ten",
                    "five",
                    "two"))
            private$..rciOV <- jmvcore::OptionOutput$new(
                "rciOV")

            self$.addOption(private$..dep)
            self$.addOption(private$..predictors)
            self$.addOption(private$..id)
            self$.addOption(private$..group)
            self$.addOption(private$..refgroup)
            self$.addOption(private$..newgroup)
            self$.addOption(private$..maximum)
            self$.addOption(private$..regtype)
            self$.addOption(private$..percentile)
            self$.addOption(private$..rciOV)
        }),
    active = list(
        dep = function() private$..dep$value,
        predictors = function() private$..predictors$value,
        id = function() private$..id$value,
        group = function() private$..group$value,
        refgroup = function() private$..refgroup$value,
        newgroup = function() private$..newgroup$value,
        maximum = function() private$..maximum$value,
        regtype = function() private$..regtype$value,
        percentile = function() private$..percentile$value,
        rciOV = function() private$..rciOV$value),
    private = list(
        ..dep = NA,
        ..predictors = NA,
        ..id = NA,
        ..group = NA,
        ..refgroup = NA,
        ..newgroup = NA,
        ..maximum = NA,
        ..regtype = NA,
        ..percentile = NA,
        ..rciOV = NA)
)

RCIResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "RCIResults",
    inherit = jmvcore::Group,
    active = list(
        citation = function() private$.items[["citation"]],
        modelsummary = function() private$.items[["modelsummary"]],
        anovaresults = function() private$.items[["anovaresults"]],
        scores = function() private$.items[["scores"]],
        nbelow = function() private$.items[["nbelow"]],
        IDbelow = function() private$.items[["IDbelow"]],
        newscores = function() private$.items[["newscores"]],
        newnbelow = function() private$.items[["newnbelow"]],
        newIDbelow = function() private$.items[["newIDbelow"]],
        rciOV = function() private$.items[["rciOV"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Reliable Change Index")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="citation",
                title="Citation"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="modelsummary",
                title="Summary of the model object"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="anovaresults",
                title="F-tests"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="scores",
                title="RCI scores for reference group"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="nbelow",
                title="Number of individuals in reference group presenting reliable decline"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="IDbelow",
                title="Individuals in reference group presenting reliable decline"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="newscores",
                title="RCI scores for test group"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="newnbelow",
                title="Number of individuals in test group presenting reliable decline"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="newIDbelow",
                title="Individuals in test group presenting reliable decline"))
            self$add(jmvcore::Output$new(
                options=options,
                name="rciOV",
                title="RCI",
                varTitle="RCI",
                varDescription="Calculated RCI",
                measureType="continuous"))}))

RCIBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "RCIBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "LogisticRCI",
                name = "RCI",
                version = c(1,0,0),
                options = options,
                results = RCIResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Reliable Change Index
#'
#' 
#' @param data .
#' @param dep .
#' @param predictors .
#' @param id .
#' @param group .
#' @param refgroup .
#' @param newgroup .
#' @param maximum .
#' @param regtype .
#' @param percentile .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$citation} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$modelsummary} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$anovaresults} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$scores} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$nbelow} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$IDbelow} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$newscores} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$newnbelow} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$newIDbelow} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$rciOV} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
RCI <- function(
    data,
    dep,
    predictors,
    id,
    group,
    refgroup,
    newgroup,
    maximum,
    regtype = "logistic",
    percentile) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("RCI requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(predictors)) predictors <- jmvcore::resolveQuo(jmvcore::enquo(predictors))
    if ( ! missing(id)) id <- jmvcore::resolveQuo(jmvcore::enquo(id))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(predictors), predictors, NULL),
            `if`( ! missing(id), id, NULL),
            `if`( ! missing(group), group, NULL))


    options <- RCIOptions$new(
        dep = dep,
        predictors = predictors,
        id = id,
        group = group,
        refgroup = refgroup,
        newgroup = newgroup,
        maximum = maximum,
        regtype = regtype,
        percentile = percentile)

    analysis <- RCIClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

